version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    environment:
      - JWT_SECRET=yourSecretKey
    depends_on:
      - user-service
    networks:
      - erp_network

  user-service:
    build: ../user-service
    ports:
      - "3002:3002"
    networks:
      - erp_network

networks:
  erp_network:
    driver: bridge
